### ISSUE TITLE
Enable a Ken Burns effect for image transitions

### ISSUE THREAD

**Issue by KrofDrakula** [miharekar/mrsi-gallery#5]
Bonus points for implementing [them](http://en.wikipedia.org/wiki/Ken_Burns_effect) via generated CSS3 animations. ;)

**Comment by miharekar** [comment]
I dont know if that would look particularly good full screen :/

**Comment by KrofDrakula** [comment]
As long as the animations are very subtle and slow (ie. not changing size and position by more than 5% and transitioning in at least 10-15 seconds), I think it could look cool.

**Comment by miharekar** [comment]
Example?

**Comment by KrofDrakula** [comment]
Quick example: [youtube](http://www.youtube.com/watch?v=l7JYAgEh5Xk&feature=related). Ignore the guy zooming in, but slow this down with less zooming and you're pretty much in the range I'm talking about.
